baseURL = "http://kevn.dev/"
languageCode = "en-us"
title = "Kevin Nguyen"
theme= "custom"

[[menus.main]]
    Name = "about"
    URL = "/about"

[[menus.main]]
    Name = "projects"
    URL = "/projects"